plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mabat.media'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mabat.installer'
        minSdk 23
        targetSdk 35
        versionCode 17
        versionName 'v1.7'
    }

    packaging {
        resources {
            excludes += ['META-INF/versions/9/OSGI-INF/MANIFEST.MF']
        }
    }

    flavorDimensions "mode"
    productFlavors {
        installer {
            dimension "mode"
            applicationId 'com.mabat.installer'
        }
        tikdosTemplate {
            dimension "mode"
            applicationId 'com.mabat.media'
        }
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.78.1'
    implementation 'androidx.core:core:1.15.0'
}